const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const os = require('node:os')
const path = require('node:path')
const fixture = require('../fixtures/camden-1540-vine.json')
const { createStore } = require('../electron/store.cjs')

async function main() {
  assert.equal(fixture.sheets['Unit Matrix'].rows.length, 287)
  assert.equal(fixture.sheets['Legal Fronts'].rows.length, 41)
  assert.equal(fixture.sheets['Evidence Registry'].rows.length, 32)
  assert.equal(fixture.sheets['Critical Clocks'].rows.length, 13)
  const storePath = path.join(os.tmpdir(), `clo-camden-fixture-${Date.now()}.json`)
  try {
    const store = await createStore(storePath)
    const data = store.snapshot()
    assert.equal(data.matter.name, '1540 N. Vine / Vinyl Hollywood')
    assert.equal(data.units.length, 287)
    assert.equal(data.legalClaims.length, 41)
    assert.equal(data.legalElements.length > 0, true)
    assert.equal(data.elementRequirements.length, 41)
    assert.equal(data.authorities.length, data.law.length)
    if (data.machine?.sourceWorkbook) {
      assert.equal(data.unitMatrixDetailed.length, 287)
      assert.equal(data.machineFronts.length, 12)
      assert.equal(data.machineAuthorities.length, 39)
      assert.equal(data.evidenceHolds.length, 15)
      assert.equal(data.activationSequence.length, 13)
      assert.equal(data.damagesModel.length, 9)
      assert.equal(data.sourceCatalog.length, 32)
      assert.equal(data.caseInputs.length, 13)
      const held = await store.applyAction('create-preservation-hold', { holdId: 'EH-2' })
      assert.ok(held.evidenceGaps.some((item) => item.evidenceHoldId === 'EH-2'))
      const activated = await store.applyAction('record-activation', { activationId: 'AS-1' })
      assert.ok(activated.machineActions.some((item) => item.activationId === 'AS-1' && item.type === 'ACTIVATION'))
      const linked = await store.applyAction('link-machine-front', { frontId: 'MF-1', targetType: 'evidenceHold', targetId: 'EH-2' })
      assert.ok(linked.machineLinks.some((item) => item.frontId === 'MF-1' && item.targetId === 'EH-2'))
      const authorityLinked = await store.applyAction('link-machine-front', { frontId: 'MF-1', targetType: 'machineAuthority', targetId: 'MP-2' })
      assert.ok(authorityLinked.machineLinks.some((item) => item.frontId === 'MF-1' && item.targetId === 'MP-2' && item.targetType === 'machineAuthority'))
      const unitLinked = await store.applyAction('link-machine-unit', { unitId: data.unitMatrixDetailed[0].id, targetType: 'machineFront', targetId: 'MF-1' })
      assert.ok(unitLinked.machineLinks.some((item) => item.unitId === data.unitMatrixDetailed[0].id && item.targetId === 'MF-1'))
      const reviewed = await store.applyAction('review-machine-source', { sourceId: 'SC-2' })
      assert.equal(reviewed.sourceCatalog.find((item) => item.id === 'SC-2').reviewStatus, 'REVIEWED_UNVERIFIED')
      const scheduled = await store.applyAction('create-machine-deadline', { title: 'Preservation response', date: '2026-09-15', source: 'Test source' })
      assert.ok(scheduled.deadlines.some((item) => item.title === 'Preservation response' && item.date === '2026-09-15'))
      assert.ok((await store.search('water')).some((item) => item.type === 'MACHINE FRONTS'))
      const reopened = await createStore(storePath)
      assert.ok(reopened.snapshot().machineLinks.some((item) => item.unitId === data.unitMatrixDetailed[0].id))
      assert.ok(reopened.snapshot().machineActions.some((item) => item.type === 'DEADLINE'))
    }
    assert.ok(data.context.some((item) => item.type === 'WAR_ROOM_WORKBOOK'))
    assert.ok(data.evidence.some((item) => item.id === 'EV-001' && item.status === 'MISSING'))
    assert.ok(data.procedure.some((item) => item.id === 'CL-003' && item.status.includes('ACTIVE')))
    console.log('CLO Camden fixture test passed')
  } finally { await fs.rm(storePath, { force: true }) }
}

main().catch((error) => { console.error(error); process.exitCode = 1 })
