const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const os = require('node:os')
const path = require('node:path')
const fixture = require('../fixtures/camden-1540-vine.json')
const { createStore } = require('../electron/store.cjs')

async function main() {
  assert.equal(fixture.sheets['Unit Matrix'].rows.length, 287)
  assert.equal(fixture.sheets['Legal Fronts'].rows.length, 41)
  assert.equal(fixture.sheets['Evidence Registry'].rows.length, 32)
  assert.equal(fixture.sheets['Critical Clocks'].rows.length, 13)
  const storePath = path.join(os.tmpdir(), `clo-camden-fixture-${Date.now()}.json`)
  try {
    const store = await createStore(storePath)
    const data = store.snapshot()
    assert.equal(data.matter.name, '1540 N. Vine / Vinyl Hollywood')
    assert.equal(data.units.length, 287)
    assert.equal(data.legalClaims.length, 41)
    assert.equal(data.legalElements.length > 0, true)
    assert.equal(data.elementRequirements.length, 41)
    assert.equal(data.authorities.length, data.law.length)
    assert.equal(data.trialPhases.length, 12)
    assert.equal(data.trialWitnesses.length, 4)
    assert.equal(data.trialExhibits.length, 5)
    assert.equal(data.trialTasks.length, 12)
    const phaseState = await store.applyAction('advance-trial-phase', { phaseId: 'TP-02' })
    assert.equal(phaseState.trial.currentPhaseId, 'TP-02')
    const taskState = await store.applyAction('record-trial-task', { taskId: 'TT-01', status: 'COMPLETE' })
    assert.equal(taskState.trialTasks.find((item) => item.id === 'TT-01').status, 'COMPLETE')
    const exhibitState = await store.applyAction('mark-exhibit-foundation', { exhibitId: 'TX-01', witnessId: 'TW-01' })
    assert.equal(exhibitState.trialExhibits.find((item) => item.id === 'TX-01').foundationStatus, 'READY_FOR_FOUNDATION')
    const objectionState = await store.applyAction('record-trial-objection', { ground: 'HEARSAY', target: 'PX-001 statement', preserved: true })
    assert.ok(objectionState.trialObjections.some((item) => item.id.startsWith('trial-objection-') && item.preserved))
    const rulingState = await store.applyAction('record-trial-ruling', { targetType: 'trialObjection', targetId: objectionState.trialObjections.at(-1).id, result: 'SUSTAINED', preserved: true })
    assert.ok(rulingState.trialRulings.some((item) => item.result === 'SUSTAINED' && item.preserved))
    const examinationState = await store.applyAction('record-examination', { examinationId: 'TE-01', status: 'COMPLETE', notes: 'Foundation and timeline covered.' })
    assert.equal(examinationState.trialExaminations.find((item) => item.id === 'TE-01').status, 'COMPLETE')
    const appealState = await store.applyAction('record-appeal-issue', { issue: 'Ruling excluded authenticated exhibit', recordLocation: 'Transcript page 42', preservation: 'PRESERVED' })
    assert.ok(appealState.trialAppealIssues.some((item) => item.preservation === 'PRESERVED'))
    const verdictState = await store.applyAction('record-verdict', { verdict: 'Judgment for plaintiff on supported claims', source: 'Test verdict record' })
    assert.equal(verdictState.trialJudgments[0].verdictStatus, 'RECORDED')
    const judgmentState = await store.applyAction('record-judgment', { entryDate: '2026-10-01', relief: 'Limited relief', source: 'Test judgment record' })
    assert.equal(judgmentState.trialJudgments[0].judgmentStatus, 'ENTERED')
    assert.equal(judgmentState.trialJudgments[0].entryDate, '2026-10-01')
    const costState = await store.applyAction('record-trial-cost', { costId: 'TC-01', amount: 125, status: 'RECORDED', source: 'Test cost record' })
    assert.equal(costState.trialCosts.find((item) => item.id === 'TC-01').amount, 125)
    const enforcementState = await store.applyAction('record-enforcement-step', { stepId: 'TEF-01', status: 'RECORDED', recordLocation: 'Test enforcement record' })
    assert.equal(enforcementState.trialEnforcement.find((item) => item.id === 'TEF-01').status, 'RECORDED')
    const appellateState = await store.applyAction('record-appellate-step', { stepId: 'TA-01', status: 'RECORDED', dueDate: '2026-10-20', recordLocation: 'Test appellate docket' })
    assert.equal(appellateState.trialAppeals.find((item) => item.id === 'TA-01').status, 'RECORDED')
    assert.equal(appellateState.trialAppeals.find((item) => item.id === 'TA-01').dueDate, '2026-10-20')
    const motionState = await store.applyAction('record-trial-motion', { motionId: 'TM-01', status: 'FILED', source: 'Test motion rule' })
    assert.equal(motionState.trialMotions.find((item) => item.id === 'TM-01').status, 'FILED')
    const instructionState = await store.applyAction('record-jury-instruction', { instructionId: 'JI-01', status: 'PROPOSED', source: 'Test instruction source' })
    assert.equal(instructionState.juryInstructions.find((item) => item.id === 'JI-01').status, 'PROPOSED')
    const witnessState = await store.applyAction('record-witness-foundation', { witnessId: 'TW-01', status: 'FOUNDATION_RECORDED', note: 'Test transcript foundation' })
    assert.equal(witnessState.trialWitnesses.find((item) => item.id === 'TW-01').status, 'FOUNDATION_RECORDED')
    const admissionState = await store.applyAction('record-exhibit-admission', { exhibitId: 'TX-01', result: 'ADMITTED', source: 'Test court ruling' })
    assert.equal(admissionState.trialExhibits.find((item) => item.id === 'TX-01').status, 'ADMITTED')
    const eventState = await store.applyAction('record-trial-event', { title: 'Opening statement delivered', date: '2026-09-10', source: 'Test transcript' })
    assert.ok(eventState.trialEvents.some((item) => item.title === 'Opening statement delivered' && item.date === '2026-09-10'))
    const argumentState = await store.applyAction('record-trial-argument', { side: 'PLAINTIFF', segment: 'OPENING', text: 'The evidence will show the supported elements.', source: 'Test trial notes' })
    assert.ok(argumentState.trialArguments.some((item) => item.segment === 'OPENING' && item.side === 'PLAINTIFF'))
    assert.ok((await store.search('opening statement')).some((item) => item.type === 'TRIAL EVENTS'))
    assert.ok((await store.search('supported elements')).some((item) => item.type === 'ARGUMENTS'))
    await assert.rejects(() => store.applyAction('record-verdict', { verdict: '' }), /Verdict requires a recorded result/)
    await assert.rejects(() => store.applyAction('record-judgment', { entryDate: 'October 1, 2026' }), /Judgment entry date requires YYYY-MM-DD/)
    await assert.rejects(() => store.applyAction('record-trial-event', { title: 'Invalid date', date: 'soon' }), /Trial event date requires YYYY-MM-DD/)
    await assert.rejects(() => store.applyAction('record-exhibit-admission', { exhibitId: 'TX-01', result: 'MAYBE' }), /Exhibit admission result is invalid/)
    if (data.machine?.sourceWorkbook) {
      assert.equal(data.unitMatrixDetailed.length, 287)
      assert.equal(data.machineFronts.length, 12)
      assert.equal(data.machineAuthorities.length, 39)
      assert.equal(data.evidenceHolds.length, 15)
      assert.equal(data.activationSequence.length, 13)
      assert.equal(data.damagesModel.length, 9)
      assert.equal(data.sourceCatalog.length, 32)
      assert.equal(data.caseInputs.length, 13)
      const held = await store.applyAction('create-preservation-hold', { holdId: 'EH-2' })
      assert.ok(held.evidenceGaps.some((item) => item.evidenceHoldId === 'EH-2'))
      const activated = await store.applyAction('record-activation', { activationId: 'AS-1' })
      assert.ok(activated.machineActions.some((item) => item.activationId === 'AS-1' && item.type === 'ACTIVATION'))
      const linked = await store.applyAction('link-machine-front', { frontId: 'MF-1', targetType: 'evidenceHold', targetId: 'EH-2' })
      assert.ok(linked.machineLinks.some((item) => item.frontId === 'MF-1' && item.targetId === 'EH-2'))
      const authorityLinked = await store.applyAction('link-machine-front', { frontId: 'MF-1', targetType: 'machineAuthority', targetId: 'MP-2' })
      assert.ok(authorityLinked.machineLinks.some((item) => item.frontId === 'MF-1' && item.targetId === 'MP-2' && item.targetType === 'machineAuthority'))
      const unitLinked = await store.applyAction('link-machine-unit', { unitId: data.unitMatrixDetailed[0].id, targetType: 'machineFront', targetId: 'MF-1' })
      assert.ok(unitLinked.machineLinks.some((item) => item.unitId === data.unitMatrixDetailed[0].id && item.targetId === 'MF-1'))
      const reviewed = await store.applyAction('review-machine-source', { sourceId: 'SC-2' })
      assert.equal(reviewed.sourceCatalog.find((item) => item.id === 'SC-2').reviewStatus, 'REVIEWED_UNVERIFIED')
      const scheduled = await store.applyAction('create-machine-deadline', { title: 'Preservation response', date: '2026-09-15', source: 'Test source' })
      assert.ok(scheduled.deadlines.some((item) => item.title === 'Preservation response' && item.date === '2026-09-15'))
      assert.ok((await store.search('water')).some((item) => item.type === 'MACHINE FRONTS'))
      const reopened = await createStore(storePath)
      assert.ok(reopened.snapshot().machineLinks.some((item) => item.unitId === data.unitMatrixDetailed[0].id))
      assert.ok(reopened.snapshot().machineActions.some((item) => item.type === 'DEADLINE'))
    }
    assert.ok(data.context.some((item) => item.type === 'WAR_ROOM_WORKBOOK'))
    assert.ok(data.evidence.some((item) => item.id === 'EV-001' && item.status === 'MISSING'))
    assert.ok(data.procedure.some((item) => item.id === 'CL-003' && item.status.includes('ACTIVE')))
    console.log('CLO Camden fixture test passed')
  } finally { await fs.rm(storePath, { force: true }) }
}

main().catch((error) => { console.error(error); process.exitCode = 1 })
