const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')
const shell = read('clo/index.html')
const preload = read('electron/preload.cjs')
const main = read('electron/main.cjs')
const css = read('clo/styles.css')
const capture = read('scripts/capture-screenshots.cjs')
const ledger = JSON.parse(read('docs/MASTER-LEDGER.json'))
const registry = JSON.parse(read('docs/source-registry.json'))

for (const route of ['command', 'evidence', 'law', 'elements', 'procedure', 'strategy', 'moderate', 'drafts', 'deadlines', 'coverage', 'machine', 'trial', 'system', 'field-atlas', 'cicero']) assert.match(shell, new RegExp(`data-route="${route}"`), `${route} route missing`)
for (const token of ['--ink-0: #0c0e12', '--ink-1: #151820', '--bone: #eee9de', '--cobalt: #4263eb', '--ochre: #d5a33e', '--oxide: #ae493c', '--viridian: #3f7d63', '--violet: #7259a8']) assert.match(css, new RegExp(token), `${token} token missing`)
assert.match(css, /grid-template-columns: 72px/)
assert.match(css, /grid-template-rows: 56px minmax\(0, 1fr\) 28px/)
assert.match(main, /contextIsolation: true/)
assert.match(main, /nodeIntegration: false/)
assert.doesNotMatch(preload, /exposeInMainWorld\(['"]node['"]|fs\./)
assert.match(preload, /linkEvidence/)
assert.match(read('clo/renderer.js'), /commit-evidence-link/)
assert.match(read('clo/renderer.js'), /runEvidenceLink/)
assert.match(read('clo/renderer.js'), /review-authority-source/)
assert.match(read('clo/renderer.js'), /runLawReview/)
assert.match(read('clo/renderer.js'), /link-element-fact/)
assert.match(read('clo/renderer.js'), /runElementAuthorityLink/)
assert.match(read('electron/store.cjs'), /Authority review requires excerpt, source page, version, effective date, jurisdiction, and limitations/)
assert.match(preload, /stageDroppedEvidence/)
assert.match(preload, /ledgerRequirements/)
assert.match(preload, /deriveDeadlines/)
assert.match(preload, /evidenceManifest/)
assert.match(preload, /backupSnapshot/)
assert.match(preload, /ledger:/)
assert.match(read('clo/renderer.js'), /machine-unit-search/)
assert.match(read('clo/renderer.js'), /link-machine-front/)
assert.match(read('clo/renderer.js'), /machine-create-deadline/)
assert.match(read('clo/renderer.js'), /SOURCECATALOG/)
assert.match(read('clo/renderer.js'), /trial-record-objection/)
assert.match(read('clo/renderer.js'), /trial-record-appeal/)
assert.match(read('clo/renderer.js'), /trial-record-verdict/)
assert.match(read('clo/renderer.js'), /trial-record-judgment/)
assert.match(read('clo/renderer.js'), /Court judgment record source or docket location/)
assert.match(read('clo/renderer.js'), /Amount in the cost record/)
assert.match(read('clo/renderer.js'), /trial-record-event/)
assert.match(read('clo/renderer.js'), /trial-record-argument/)
assert.match(read('clo/renderer.js'), /record-procedure-event/)
assert.match(read('clo/renderer.js'), /record-procedure-filing/)
assert.match(read('clo/renderer.js'), /record-procedure-service/)
assert.match(read('clo/renderer.js'), /record-procedure-docket/)
assert.match(read('electron/store.cjs'), /action === 'record-filing'/)
assert.match(read('electron/store.cjs'), /action === 'record-service'/)
assert.match(read('electron/store.cjs'), /action === 'record-docket-entry'/)
assert.match(css, /\.deadline-bar\.high/)
assert.match(read('clo/renderer.js'), /consequence.*consequence/)
assert.match(read('electron/store.cjs'), /validationChecks/)
assert.match(read('electron/store.cjs'), /Authority requires an HTTP\(S\) source URL/)
assert.match(read('clo/renderer.js'), /recalculate-completeness/)
assert.match(read('clo/renderer.js'), /trial-ruling-reasoning/)
assert.match(read('clo/renderer.js'), /record-moderation-review/)
assert.match(read('clo/renderer.js'), /event.key === '0'/)
assert.match(capture, /'machine'/)
assert.match(capture, /'moderate'/)
assert.match(capture, /disableHardwareAcceleration/)
assert.match(capture, /disable-gpu/)
assert.equal(ledger.total, 2820)
assert.equal(ledger.requirements.length, 2820)
assert.ok(registry.attachmentCount >= 1)
console.log('CLO constitution test passed')
