const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')
const shell = read('clo/index.html')
const preload = read('electron/preload.cjs')
const main = read('electron/main.cjs')
const css = read('clo/styles.css')

for (const route of ['command', 'evidence', 'law', 'elements', 'procedure', 'strategy', 'drafts', 'deadlines', 'coverage', 'system', 'field-atlas', 'cicero']) assert.match(shell, new RegExp(`data-route="${route}"`), `${route} route missing`)
for (const token of ['--ink-0: #0c0e12', '--ink-1: #151820', '--bone: #eee9de', '--cobalt: #4263eb', '--ochre: #d5a33e', '--oxide: #ae493c', '--viridian: #3f7d63', '--violet: #7259a8']) assert.match(css, new RegExp(token), `${token} token missing`)
assert.match(css, /grid-template-columns: 72px/)
assert.match(css, /grid-template-rows: 56px minmax\(0, 1fr\) 28px/)
assert.match(main, /contextIsolation: true/)
assert.match(main, /nodeIntegration: false/)
assert.doesNotMatch(preload, /exposeInMainWorld\(['"]node['"]|fs\./)
assert.match(preload, /linkEvidence/)
assert.match(preload, /deriveDeadlines/)
console.log('CLO constitution test passed')
